### Get all the data available in the database
GET http://localhost:3001/data/

### Get With respect to id 
GET http://localhost:3001/data/6/

### Insert new data in the table

POST http://localhost:3001/data/
Content-Type: application/json

{
    "name": "Andro",
    "imageUrl": "https://img.freepik.com/free-photo/close-up-portrait-young-hindu-man-isolated-black-studio-wall_155003-29352.jpg?ga=GA1.1.1041120550.1692680325&semt=ais_user",
    "city": "Los Angeles"
}

### Updating name in the table

POST http://localhost:3001/data/2
Content-Type: application/json

{
    "name": "Lala"
}