### Get all the data available in the database
GET http://localhost:3001/users/

### insert the data into table

POST http://localhost:3001/signUp/
Content-Type: application/json

{
    "name": "chintu_chita",
    "password": "chintu"
}

### login api 

POST http://localhost:3001/login
Content-Type: application/json

{
    "name": "lala",
    "password": "lala123"
}